# Generated by Django 4.2.27 on 2026-01-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='verification_pin',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
